name: firefox-docker
on: workflow_dispatch
jobs:
  firefox-no-docker:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: firefox --version
    - run: npx cypress run --browser firefox

  firefox-docker:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-20.6.1-chrome-116.0.5845.187-1-ff-117.0-edge-116.0.1938.76-1
      options: --user 1001
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: firefox --version
    - run: npx cypress run --browser firefox

  firefox-docker-cy-gha-1001:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-20.6.1-chrome-116.0.5845.187-1-ff-117.0-edge-116.0.1938.76-1
      options: --user 1001
    steps:
    - uses: actions/checkout@v4
    - run: firefox --version
    - uses: cypress-io/github-action@v6
      with:
        browser: firefox

  firefox-docker-root:
    runs-on: ubuntu-22.04
    container: cypress/browsers:node-20.6.1-chrome-116.0.5845.187-1-ff-117.0-edge-116.0.1938.76-1
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: firefox --version
    - run: npx cypress info
      if: always()
    - run: npx cypress run --browser firefox
      if: always()

  firefox-docker-cy-gha-root:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-20.6.1-chrome-116.0.5845.187-1-ff-117.0-edge-116.0.1938.76-1
    steps:
      - uses: actions/checkout@v4
      - run: firefox --version
      - run: npx cypress info
        if: always()
      - uses: cypress-io/github-action@v6
        if: always()
        with:
          browser: firefox
