name: firefox-docker-debug
on: workflow_dispatch
env:
  DEBUG: 'cypress:launcher:*,cypress-verbose:launcher:*'
jobs:

  firefox-docker:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
      options: --user 1001
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: firefox --version
    - run: npx cypress run --browser firefox

  firefox-docker-latest:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:latest
      options: --user 1001
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: firefox --version
    - run: npx cypress run --browser firefox

  firefox-docker-root:
    runs-on: ubuntu-22.04
    container: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: firefox --version
    - run: npx cypress info
      if: always()
    - run: npx cypress run --browser firefox
      if: always()

  firefox-docker-root-latest:
    runs-on: ubuntu-22.04
    container: cypress/browsers:latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: firefox --version
    - run: npx cypress info
      if: always()
    - run: npx cypress run --browser firefox
      if: always()
