name: firefox-docker
on: workflow_dispatch
jobs:
  firefox-no-docker:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: firefox --version
    - run: npx cypress run --browser firefox

  firefox-docker:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
      options: --user 1001
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: firefox --version
    - run: npx cypress run --browser firefox

  firefox-docker-cy-gha-1001:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
      options: --user 1001
    steps:
    - uses: actions/checkout@v3
    - run: firefox --version
    - uses: cypress-io/github-action@v5
      with:
        browser: firefox

  firefox-docker-root:
    runs-on: ubuntu-22.04
    container: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: firefox --version
    - run: npx cypress info
      if: always()
    - run: npx cypress run --browser firefox
      if: always()

  firefox-docker-cy-gha-root:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
    steps:
      - uses: actions/checkout@v3
      - run: firefox --version
      - run: npx cypress info
        if: always()
      - uses: cypress-io/github-action@v5
        if: always()
        with:
          browser: firefox
