name: firefox-docker-success
on: workflow_dispatch

jobs:
  firefox-no-docker:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: firefox --version
    - run: npx cypress run --browser firefox

  firefox-docker-user-1001:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    container:
      image: cypress/browsers:latest
      options: --user 1001
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: firefox --version
    - run: npx cypress run --browser firefox

  firefox-docker-cy-gha-1001:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    container:
      image: cypress/browsers:latest
      options: --user 1001
    steps:
    - uses: actions/checkout@v4
    - run: firefox --version
    - uses: cypress-io/github-action@v6
      with:
        browser: firefox
