name: firefox-docker-fail
on: workflow_dispatch
jobs:
  firefox-docker-root:
    runs-on: ubuntu-24.04
    container: cypress/browsers:latest
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: firefox --version
    - run: npx cypress info
      if: always()
    - run: npx cypress run --browser firefox
      if: always()

  firefox-docker-cy-gha-root:
    runs-on: ubuntu-24.04
    container:
      image: cypress/browsers:latest
    steps:
      - uses: actions/checkout@v4
      - run: firefox --version
      - run: npx cypress info
        if: always()
      - uses: cypress-io/github-action@v6
        if: always()
        with:
          browser: firefox
